project_id = "nqkjyrgrquzjvpicmcpf"

[functions.raw]
verify_jwt = false

[functions.admin-list]
verify_jwt = false

[functions.admin-delete]
verify_jwt = false

[functions.cleanup]
verify_jwt = false

[functions.admin-rotate]
verify_jwt = false
