# schema-drift-diff replay env/test-context (source with: set -a; . env.sh; set +a)
SCHEMA_DRIFT_DIFF_FUZZ_SEED=42
SCHEMA_DRIFT_DIFF_READER_DURATION_MS=100
SCHEMA_DRIFT_DIFF_TEST_NAME_PATTERN=pat
SCHEMA_DRIFT_DIFF_TEST_TIMEOUT_MS=30000
